GET http://localhost:8000/address/

###

GET http://localhost:8000/address/1/

###

POST http://localhost:8000/address/
Content-Type: application/json

{
  "street": "Yunosti",
  "home": 15
}

###

GET http://localhost:8000/address/1/shops/

###